### ISSUE TITLE
Ask a question about tableRegExp

### ISSUE THREAD

**Issue by zouyaoji** [tolking/components-helper#11]
This is a great project, thank you very much. In my case, some documents contain comments to assist `prettier` formatting, such as `<!-- prettier-ignore -->`, as the picture shows:

![image](https://user-images.githubusercontent.com/24430116/115055148-ae283e00-9f13-11eb-879d-e25e44918f76.png)

so I should handle this situation in tableRegExp. And this is my tableRegExp configuration.

```js
helper({
  name,
  version: _version,
  entry: 'website/docs/zh-CN/vc-entity.md',
  outDir: 'lib',
  reComponentName,
  reDocUrl,
  reAttribute,
  props: '属性',
  propsName: '属性名',
  propsDescription: '描述',
  propsType: '类型',
  propsDefault: '默认值',
  propsOptions: '可选值',
  events: '事件',
  eventsName: '事件名',
  eventsDescription: '描述',
  slots: '插槽',
  slotsName: '插槽名',
  slotsDescription: '描述',
  directives: '插槽',
  directivesName: '插槽名',
  directivesDescription: '描述',
  directivesType: '类型',
  tableRegExp: '#+\\s+(.*\\s*属性|.*\\s*事件|.*\\s*插槽|.*\\s*指令)\\s*\\n+((<!--.*?-->)*)\\n*(\\|?.+\\|.+)\\n\\|?\\s*:?-+:?\\s*\\|.+((\\n\\|?.+\\|.+)+)'
})
```
Among them, `((<!--.*?-->)*)\\n*` is what I added.
I think it looks okay, but I can’t get the correct result. I hope I can get your help.

**Comment by tolking** [comment]
`#+\\s+(.*\\s*属性|.*\\s*事件|.*\\s*插槽|.*\\s*指令)\\s*\\n*.*\\n+(\\|?.+\\|.+)\\n\\|?\\s*:?-+:?\\s*\\|.+((\\n\\|?.+\\|.+)+)`

正则里面带括号的内容会影响 `match` 匹配，所以新增的内容不能够带 `()`

**Comment by zouyaoji** [comment]
明白了。
 不是所有表格上都有  注释，那为了兼顾2个情况，
正解可能应该是把（）换成[], 即  `[<!--.*?-->]*\\n*`

但会报错。

![image](https://user-images.githubusercontent.com/24430116/115105867-28000c00-9f94-11eb-9857-88ddec81c9d5.png)


建议支持直接传 正则表达式对象？

**Comment by tolking** [comment]
我上面发的应该能够满足你的需求

**Comment by zouyaoji** [comment]
确实啊，我居然无视了正解，是我格局小了。。。

还有个别问题，我再想想，不行再来另开 issue 请教。

非常感谢
