### ISSUE TITLE
[Feature Request] make subtags

### ISSUE THREAD

**Issue by zouyaoji** [tolking/components-helper#12]
Is there a way to automatically generate subtags, or manually define subtags?

**Comment by tolking** [comment]
Welcome to provide good ideas

**Comment by zouyaoji** [comment]
I didn't think of a good way, it's better to define it in advance, you can write it in the document, and write it according to the agreed subtitle. Or simply define the parent-child component relationship to a json file, which can be passed into components-helper to generate subtags. I chose the latter.

没想到好的办法，不如提前定义好吧，可以写到文档里面，按约定的子标题写。或者干脆把父子组件关系定义到json文件中，能传进components-helper生成subtags。我选择了后者。

**Comment by tolking** [comment]
我感觉单独维护 subtags 过于麻烦，将其整合到 slots 里面可能是一个更好的选择

```md
### Slots

| Name | Description | Subtags |
| -- | -- | -- |
| default | slot | Checkbox / Radio |
```

**Comment by zouyaoji** [comment]
好的。我发现一个问题，不知道是不是问题哈，就是可选值，好像只有String的能提取出来，数值的提取不出来呢？

**Comment by tolking** [comment]
vetur 的可选值只支持 string 补全，详情可以去看源码

**Comment by zouyaoji** [comment]
原来如此
